Failure # 1 (occurred at 2023-07-25_13-56-39)
[36mray::A2C.train()[39m (pid=62748, ip=127.0.0.1, actor_id=73fde2b571981be4b44dea7501000000, repr=A2C)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 389, in train
    raise skipped from exception_cause(skipped)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 386, in train
    result = self.step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 803, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2853, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/a2c/a2c.py", line 174, in training_step
    return Algorithm.training_step(self)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 1378, in training_step
    train_batch = synchronous_parallel_sample(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.apply()[39m (pid=62749, ip=127.0.0.1, actor_id=eb94d0a7d9695fe47abe5ffc01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x15020a280>)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 185, in apply
    raise e
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 616, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/connectors/agent/pipeline.py", line 41, in __call__
    ret = c(ret)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/connectors/connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/connectors/connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/connectors/agent/obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/models/preprocessors.py", line 206, in transform
    self.check_shape(observation)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/models/preprocessors.py", line 74, in check_shape
    raise ValueError(
ValueError: Observation ([102.26383  102.5445   101.93781   17.567875  16.6     ] dtype=float32) outside given space (Box([  0.   0.   0.   0. -50.], [ 50.  50.  50. 100.  60.], (5,), float32))!
